frameworkVersion: "1.1.0"

service: ${file(../config.yml):appPrefix}-items

provider:
  name: aws
  runtime: ${file(../config.yml):awsRuntime}
  stage: ${file(../config.yml):awsStage}
  region: ${file(../config.yml):awsRegion}
  profile: ${file(../config.yml):awsProfile}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${file(../config.yml):awsRegion}:*:*"

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: items
          method: post
          cors: true
  readAll:
    handler: handler.readAll
    events:
      - http:
          path: items
          method: get
          cors: true
  read:
    handler: handler.read
    events:
      - http:
          path: items/{id}
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: items/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: items/{id}
          method: delete
          cors: true

package:
  exclude:
    - node_modules/**
    - '!node_modules/lib/**'

plugins:
  - serverless-offline