
# consolidating core configurations between your services
awsRuntime: nodejs4.3
awsStage: test
awsRegion: us-east-1
awsProfile: av_serverless_admin

# and load any other variables you want :)
appPrefix: hq-serverless-crud
awsDynamoDbTablePrefix: hq-serverless-crud-
